{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52dce39310>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_for_authorization","uid":"1cfd6a7639699854","parentUid":"5e0fbce7127d36e40447743c5335cf24","status":"broken","time":{"start":1691353789961,"stop":1691353789961,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"5e0fbce7127d36e40447743c5335cf24"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}