WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f13ad45b1d0>: Failed to resolve 'none' ([Errno -3] Temporary failure in name resolution)")': /session
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f13ad45bbd0>: Failed to resolve 'none' ([Errno -3] Temporary failure in name resolution)")': /session
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f13ad460750>: Failed to resolve 'none' ([Errno -3] Temporary failure in name resolution)")': /session